In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

%config InlineBackend.figure_format = 'svg'

In [2]:
df = pd.read_csv("Online Dataset.csv")

In [3]:
df

,Unnamed: 0,Epochs,Current_State,Pit_Position,Goal_Position,Wall_Position,Action,Reward,Next_State,Epsilon_Boolean,Q_Max,Q1_Current,Q2_Current,Q3_Current,Q4_Current,Q1_Next,Q2_Next,Q3_Next,Q4_Next
0,0,0,8,10,12,9,3,-1,8,0,0.091794,-0.065128,-0.084517,0.054154,0.091794,-0.065416,-0.084419,0.053967,0.092021
1,1,0,8,10,12,9,3,-1,8,0,0.092021,-0.065416,-0.084419,0.053967,0.092021,-0.065042,-0.084073,0.054280,0.092051
2,2,0,8,10,12,9,3,-1,8,0,0.092051,-0.065042,-0.084073,0.054280,0.092051,-0.065421,-0.084044,0.054130,0.092035
3,3,0,8,10,12,9,3,-1,8,0,0.092035,-0.065421,-0.084044,0.054130,0.092035,-0.065540,-0.084577,0.054154,0.092471
4,4,0,8,10,12,9,3,-1,8,0,0.092471,-0.065540,-0.084577,0.054154,0.092471,-0.065336,-0.084862,0.054133,0.091836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33060,33060,4999,2,15,14,13,1,-1,6,0,6.129316,3.491375,6.129316,2.507191,2.216899,3.118028,8.377428,3.581647,4.995778
33061,33061,4999,6,15,14,13,2,-1,5,1,8.360590,3.091562,8.360590,3.576749,5.000494,2.115431,6.833839,4.550787,5.135643
33062,33062,4999,5,15,14,13,1,-1,9,0,6.809101,2.090010,6.809101,4.536398,5.135134,2.390096,4.991859,4.299376,8.889229
33063,33063,4999,9,15,14,13,3,-1,10,0,8.909819,2.361672,4.966386,4.306787,8.909819,3.343138,9.182156,5.461194,5.354160
33064,33064,4999,10,15,14,13,1,10,14,0,9.178448,3.301888,9.178448,5.485474,5.371994,4.919349,5.658956,5.035061,3.437227

In [4]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
df

,Epochs,Current_State,Pit_Position,Goal_Position,Wall_Position,Action,Reward,Next_State,Epsilon_Boolean,Q_Max,Q1_Current,Q2_Current,Q3_Current,Q4_Current,Q1_Next,Q2_Next,Q3_Next,Q4_Next
0,0,8,10,12,9,3,-1,8,0,0.091794,-0.065128,-0.084517,0.054154,0.091794,-0.065416,-0.084419,0.053967,0.092021
1,0,8,10,12,9,3,-1,8,0,0.092021,-0.065416,-0.084419,0.053967,0.092021,-0.065042,-0.084073,0.054280,0.092051
2,0,8,10,12,9,3,-1,8,0,0.092051,-0.065042,-0.084073,0.054280,0.092051,-0.065421,-0.084044,0.054130,0.092035
3,0,8,10,12,9,3,-1,8,0,0.092035,-0.065421,-0.084044,0.054130,0.092035,-0.065540,-0.084577,0.054154,0.092471
4,0,8,10,12,9,3,-1,8,0,0.092471,-0.065540,-0.084577,0.054154,0.092471,-0.065336,-0.084862,0.054133,0.091836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33060,4999,2,15,14,13,1,-1,6,0,6.129316,3.491375,6.129316,2.507191,2.216899,3.118028,8.377428,3.581647,4.995778
33061,4999,6,15,14,13,2,-1,5,1,8.360590,3.091562,8.360590,3.576749,5.000494,2.115431,6.833839,4.550787,5.135643
33062,4999,5,15,14,13,1,-1,9,0,6.809101,2.090010,6.809101,4.536398,5.135134,2.390096,4.991859,4.299376,8.889229
33063,4999,9,15,14,13,3,-1,10,0,8.909819,2.361672,4.966386,4.306787,8.909819,3.343138,9.182156,5.461194,5.354160
33064,4999,10,15,14,13,1,10,14,0,9.178448,3.301888,9.178448,5.485474,5.371994,4.919349,5.658956,5.035061,3.437227

In [6]:
pc = df[df["Epsilon_Boolean"] == 0]
pc

,Epochs,Current_State,Pit_Position,Goal_Position,Wall_Position,Action,Reward,Next_State,Epsilon_Boolean,Q_Max,Q1_Current,Q2_Current,Q3_Current,Q4_Current,Q1_Next,Q2_Next,Q3_Next,Q4_Next
0,0,8,10,12,9,3,-1,8,0,0.091794,-0.065128,-0.084517,0.054154,0.091794,-0.065416,-0.084419,0.053967,0.092021
1,0,8,10,12,9,3,-1,8,0,0.092021,-0.065416,-0.084419,0.053967,0.092021,-0.065042,-0.084073,0.054280,0.092051
2,0,8,10,12,9,3,-1,8,0,0.092051,-0.065042,-0.084073,0.054280,0.092051,-0.065421,-0.084044,0.054130,0.092035
3,0,8,10,12,9,3,-1,8,0,0.092035,-0.065421,-0.084044,0.054130,0.092035,-0.065540,-0.084577,0.054154,0.092471
4,0,8,10,12,9,3,-1,8,0,0.092471,-0.065540,-0.084577,0.054154,0.092471,-0.065336,-0.084862,0.054133,0.091836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33058,4998,2,13,3,9,3,10,3,0,10.648301,9.667162,8.104548,8.723117,10.648301,9.750537,7.236125,9.528656,9.365549
33060,4999,2,15,14,13,1,-1,6,0,6.129316,3.491375,6.129316,2.507191,2.216899,3.118028,8.377428,3.581647,4.995778
33062,4999,5,15,14,13,1,-1,9,0,6.809101,2.090010,6.809101,4.536398,5.135134,2.390096,4.991859,4.299376,8.889229
33063,4999,9,15,14,13,3,-1,10,0,8.909819,2.361672,4.966386,4.306787,8.909819,3.343138,9.182156,5.461194,5.354160
33064,4999,10,15,14,13,1,10,14,0,9.178448,3.301888,9.178448,5.485474,5.371994,4.919349,5.658956,5.035061,3.437227

In [7]:
def foo(x):
    m = pd.Series.mode(x)
    if len(m) == 1: 
        return m

pc = pc.groupby(['Current_State', 'Next_State', 'Pit_Position', 'Goal_Position', 'Wall_Position', 'Q_Max']).Action.apply(foo).reset_index(level=1, drop=True).reset_index()
pc

,Current_State,Pit_Position,Goal_Position,Wall_Position,Q_Max,level_5,Action
0,0,1,5,8,-5.488395,0,0
1,0,1,5,8,-4.943810,0,0
2,0,1,5,8,-4.491105,0,0
3,0,1,5,8,-4.184905,0,0
4,0,1,5,8,-4.030087,0,0
...,...,...,...,...,...,...,...
23182,15,14,13,3,4.189399,0,1
23183,15,14,13,11,1.650604,0,0
23184,15,14,13,11,1.773155,0,0
23185,15,14,13,11,1.784922,0,0
23186,15,14,13,11,1.820844,0,0

In [8]:
pc.drop('level_5', axis=1, inplace=True)
pc

,Current_State,Pit_Position,Goal_Position,Wall_Position,Q_Max,Action
0,0,1,5,8,-5.488395,0
1,0,1,5,8,-4.943810,0
2,0,1,5,8,-4.491105,0
3,0,1,5,8,-4.184905,0
4,0,1,5,8,-4.030087,0
...,...,...,...,...,...,...
23182,15,14,13,3,4.189399,1
23183,15,14,13,11,1.650604,0
23184,15,14,13,11,1.773155,0
23185,15,14,13,11,1.784922,0
23186,15,14,13,11,1.820844,0

In [9]:
pc = pc.drop_duplicates(keep='last',subset=['Current_State', 'Pit_Position', 'Goal_Position', 'Wall_Position'])
pc

,Current_State,Pit_Position,Goal_Position,Wall_Position,Q_Max,Action
19,0,1,7,6,3.852308,0
43,0,1,14,12,1.757879,2
57,0,2,15,14,-1.899345,0
59,0,3,1,13,9.893638,0
80,0,3,11,9,-2.104496,0
...,...,...,...,...,...,...
23169,15,14,8,4,2.583724,3
23171,15,14,10,2,6.072558,1
23172,15,14,12,10,1.383503,3
23182,15,14,13,3,4.189399,1
23186,15,14,13,11,1.820844,0

In [10]:
pc.describe()

,Current_State,Pit_Position,Goal_Position,Wall_Position,Q_Max,Action
count,11302.000000,11302.000000,11302.000000,11302.000000,11302.000000,11302.000000
mean,7.474960,7.535392,7.458061,7.477703,6.274280,1.528667
std,4.249064,4.562705,4.721831,4.565405,3.539920,1.109611
min,0.000000,0.000000,0.000000,0.000000,-19.146124,0.000000
25%,4.000000,4.000000,3.000000,4.000000,4.588993,1.000000
50%,7.000000,8.000000,7.000000,7.000000,6.825121,1.000000
75%,11.000000,12.000000,12.000000,11.000000,8.795183,3.000000
max,15.000000,15.000000,15.000000,15.000000,14.948278,3.000000

In [11]:
pc.groupby(['Action'])['Action'].count().sort_values(ascending=False)

Action
1    3100
3    2957
2    2653
0    2592
Name: Action, dtype: int64

In [12]:
X = pc[['Current_State','Pit_Position', 'Goal_Position', 'Wall_Position']].values
y = pc[['Q_Max']].values

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/5, random_state = 0)

In [14]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [15]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

2.6268543970959706

In [16]:
from math import sqrt
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = sqrt(mse)
rmse

3.4357464372785222

In [17]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.004133994843191546

In [18]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test, y_pred)

11.562595877866038

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

In [47]:
x_train_full, x_test, y_train_full, y_test = train_test_split(X, y, test_size = 1/5, random_state = 0)
x_train, x_validation, y_train, y_validation = train_test_split(x_train_full, y_train_full)

In [48]:
model = tf.keras.Sequential([tf.keras.layers.Dense(30, activation = 'relu', input_shape = x_train.shape[1:]),
                            tf.keras.layers.Dense(1)])

In [49]:
model.compile(loss = tf.losses.mean_squared_error,
             optimizer = 'sgd')

In [50]:
hostory = model.fit(x_train, y_train, epochs=20,
                   validation_data=(x_validation, y_validation))

Epoch 1/20
212/212 [==============================] - 1s 2ms/step - loss: 24.1814 - val_loss: 13.6175
Epoch 2/20
212/212 [==============================] - 0s 2ms/step - loss: 11.9974 - val_loss: 12.3579
Epoch 3/20
212/212 [==============================] - 0s 2ms/step - loss: 11.0499 - val_loss: 12.6693
Epoch 4/20
212/212 [==============================] - 1s 2ms/step - loss: 10.8645 - val_loss: 12.0385
Epoch 5/20
212/212 [==============================] - 0s 2ms/step - loss: 10.8451 - val_loss: 11.8957
Epoch 6/20
212/212 [==============================] - 0s 2ms/step - loss: 10.8800 - val_loss: 11.9498
Epoch 7/20
212/212 [==============================] - 0s 2ms/step - loss: 10.8270 - val_loss: 12.1163
Epoch 8/20
212/212 [==============================] - 1s 2ms/step - loss: 10.8813 - val_loss: 11.8898
Epoch 9/20
212/212 [==============================] - 1s 2ms/step - loss: 10.8390 - val_loss: 12.1519
Epoch 10/20
212/212 [==============================] - 1s 2ms/step - loss: 10.8567 - val_loss: 11.8579
Epoch 11/20
212/212 [==============================] - 1s 2ms/step - loss: 10.8212 - val_loss: 11.9008
Epoch 12/20
212/212 [==============================] - 1s 2ms/step - loss: 10.8416 - val_loss: 11.9065
Epoch 13/20
212/212 [==============================] - 0s 2ms/step - loss: 10.8420 - val_loss: 11.8597
Epoch 14/20
212/212 [==============================] - 0s 2ms/step - loss: 10.8437 - val_loss: 11.8566
Epoch 15/20
212/212 [==============================] - 0s 2ms/step - loss: 10.8238 - val_loss: 11.8611
Epoch 16/20
212/212 [==============================] - 0s 2ms/step - loss: 10.7864 - val_loss: 12.1384
Epoch 17/20
212/212 [==============================] - 1s 2ms/step - loss: 10.8387 - val_loss: 11.8013
Epoch 18/20
212/212 [==============================] - 0s 2ms/step - loss: 10.8198 - val_loss: 11.8683
Epoch 19/20
212/212 [==============================] - 0s 2ms/step - loss: 10.7815 - val_loss: 11.9649
Epoch 20/20
212/212 [==============================] - 0s 2ms/step - loss: 10.8269 - val_loss: 11.8284

In [51]:
mean_squared_error_test = model.evaluate(x_test, y_test)
y_pred = model.predict(x_test)
y_pred

71/71 [==============================] - 0s 2ms/step - loss: 10.1427
71/71 [==============================] - 0s 2ms/step

array([[6.571449 ],
       [7.351167 ],
       [7.351167 ],
       ...,
       [6.9652653],
       [6.511541 ],
       [4.774764 ]], dtype=float32)

In [52]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

2.3803289673669688

In [53]:
from math import sqrt
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = sqrt(mse)
rmse

3.184762019834319

In [54]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.13721332048645352

In [55]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test, y_pred)

10.01123324134293